[package]
name = "fsd"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
clap = { version = "4.2.3", features = ["derive"] }
dotenvy = "0.15.7"
globwalk = "0.8.1"
path-absolutize = "3.0.14"
rayon = "1.7.0"
repak = { git = "https://github.com/trumank/repak", version = "0.1.5" }
walkdir = "2.3.3"
zip = "0.6.4"
